name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  lint_csharp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      
    - name: Install dotnet format
      run: dotnet tool update -g dotnet-format
      
    - name: Run dotnet format
      run: dotnet format --check -v:normal

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build --configuration Release /bl

    - name: Test
      run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"
            
    - uses: actions/upload-artifact@v2
      with:
        name: logs
        if-no-files-found: warn
        retention-days: 5
        path: |
          **/*.binlog
          **/*.cobertura.xml

  build_nuget_packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Pack
      run: dotnet pack --configuration Release
      
    - uses: actions/upload-artifact@v2
      with:
        name: nuget_packages
        if-no-files-found: error
        retention-days: 5
        path: |
          **/*.nupkg
          **/*.snupkg
